credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$E/wN9HMkaO6YXplBpCx1F.DFzrcRnX3Hxxe2FfenmlYHOn0vlfITO # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$mSgFRkZHRaRLRrWfp/Spl.OngjFxnPyehQ3UKvGPEvgJTCYFs52c # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com